site_name: Единый Портал Документации
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight

plugins:
  - search

nav:
  - Главная: index.md
  - Моя страница: my_first_page.md
  - Руководства:
      - Начало работы:
          - Установка: guides/getting-started/installation.md
          - Функции: guides/getting-started/features.md
      - UML Диаграммы:
          - UML Диаграмма(mermaid): guides/uml/diagrams.md
          - UML Диаграмма(jpg): guides/uml/diagrams_jpg.md
          - UML Диаграмма gpu (jpg): guides/uml/diagrams_gpu_jpg.md
      - Помощь:
          - FAQ: guides/help/faq.md
          - Как помочь: guides/help/contributing.md
  - Сравнение конвертеров:
      - Marker (из PDF): comparison/сomparison/marker_pdf.md
      - Marker gpu (из PDF): comparison/сomparison/marker_gpu_pdf.md
      - MarkItDown (из Word): comparison/сomparison/markitdown_docx.md
      - MarkItDown (из PDF): comparison/сomparison/markitdown_pdf.md
      - Pandoc (из Word): comparison/сomparison/pandoc_docx.md
      - pymupdf4llm (из PDF): comparison/сomparison/pymupdf4llm_pdf.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
extra_javascript:
  - javascripts/mermaid.min.js
  - javascripts/mermaid-init.js

use_directory_urls: true